### ISSUE TITLE
Synthetic Dataset Generation: A few datasets related queries

### ISSUE THREAD

**Issue by fatima-dev103** [radimspetlik/SI-DDPM-FMO#4]
Dear @radimspetlik, thanks for your quick response to my questions.

Can you help me still with a few things:

1- What is the total memory of the resultant dataset you generated with the render script? I see it was 1TB as you mentioned in the readme files. I want to reproduce the results, for that, I must generate the same dataset as you generated.
2- Can you share the reference from where you get the render scripts and make changes for your purpose?
3- Can you please highlight or share the procedure you downloaded or get the sports-1m sequences?
4- Can you please mention if you have used whole sequences in the sports-1m dataset or a part of it? Can you mention highlight which part or videos you have used while dataset generation?
5- It would be great if you can also highlight the VOT dataset year, you have used while dataset generation?

**Comment by radimspetlik** [comment]
closing as this is a duplicate issue; the answers are in the original issue
